number <- seq(1:4)
name <- c("정우성", "김철수", "송중기", "김영희")
kor <- c(80,60,90,70)
eng <- c(70,50,100,80)
mat <- c(95,70,95,80)
grade <- c("B", "D", "A", "C")
stuInfo <- data.frame(number, name, kor, eng, mat, grade, stringsAsFactors = FALSE)
print(stuInfo)
str(stuInfo)
print(stuInfo)
